version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:20260
functions:
  facesdetection-python:
    lang: python3-http
    handler: ./facesdetection-python
    image: adrianoggm10/facesdetection-python:latest

