apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-files
  namespace: owncloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
